//! Single-responsibility self-signed certificate material generation.

use std::sync::Arc;

use rand_chacha::ChaCha20Rng;
use rand_core::RngCore;
use rand_core::SeedableRng;
use rcgen::{
    BasicConstraints, CertificateParams, DnType, ExtendedKeyUsagePurpose, IsCa, KeyPair,
    KeyUsagePurpose, PKCS_RSA_SHA256,
};
use rustls_pki_types::PrivatePkcs8KeyDer;
use time::Duration as TimeDuration;
use uselesskey_core::Factory;
use uselesskey_rsa::{RsaFactoryExt, RsaSpec};

use crate::srp::derive::{
    deterministic_base_time_from_parts, deterministic_serial_number_with_rng,
};
use crate::srp::spec::{NotBeforeOffset, X509Spec};

/// Generated bytes and PEM strings for a self-signed X.509 fixture.
pub(crate) struct SelfSignedMaterial {
    pub(crate) cert_der: Arc<[u8]>,
    pub(crate) cert_pem: String,
    pub(crate) private_key_pkcs8_der: Arc<[u8]>,
    pub(crate) private_key_pkcs8_pem: String,
}

struct SigningMaterial {
    key_pair: KeyPair,
    pkcs8_der: Vec<u8>,
    pkcs8_pem: String,
}

pub(crate) fn load_self_signed_material(
    factory: &Factory,
    domain: &'static str,
    label: &str,
    spec: &X509Spec,
    variant: &str,
) -> Arc<SelfSignedMaterial> {
    let spec_bytes = spec.stable_bytes();

    factory.get_or_init(domain, label, &spec_bytes, variant, |seed| {
        let mut rng = ChaCha20Rng::from_seed(*seed.bytes());
        let signing_material = signing_material(factory, label, spec);
        let params = certificate_params(label, spec, &mut rng);
        let cert = params
            .self_signed(&signing_material.key_pair)
            .expect("cert generation");

        SelfSignedMaterial {
            cert_der: Arc::from(cert.der().as_ref()),
            cert_pem: cert.pem(),
            private_key_pkcs8_der: Arc::from(signing_material.pkcs8_der),
            private_key_pkcs8_pem: signing_material.pkcs8_pem,
        }
    })
}

fn signing_material(factory: &Factory, label: &str, spec: &X509Spec) -> SigningMaterial {
    // Generate RSA key using uselesskey-rsa for deterministic key generation.
    // Keep the historical key identity tied to the certificate label and spec.
    let key_label = format!("{}-key", label);
    let rsa_keypair = factory.rsa(&key_label, RsaSpec::new(spec.rsa_bits));
    let pkcs8_der = rsa_keypair.private_key_pkcs8_der().to_vec();
    let pkcs8_pem = rsa_keypair.private_key_pkcs8_pem().to_string();
    let pkcs8_key = PrivatePkcs8KeyDer::from(pkcs8_der.clone());
    let key_pair =
        KeyPair::from_pkcs8_der_and_sign_algo(&pkcs8_key, &PKCS_RSA_SHA256).expect("key parse");

    SigningMaterial {
        key_pair,
        pkcs8_der,
        pkcs8_pem,
    }
}

fn certificate_params(label: &str, spec: &X509Spec, rng: &mut ChaCha20Rng) -> CertificateParams {
    let mut params = CertificateParams::default();
    params
        .distinguished_name
        .push(DnType::CommonName, spec.subject_cn.clone());

    let (not_before, not_after) = validity_window(label, spec);
    params.not_before = not_before;
    params.not_after = not_after;
    params.serial_number = Some(deterministic_serial_number_with_rng(|bytes| {
        rng.fill_bytes(bytes);
    }));
    params.is_ca = ca_constraint(spec);
    params.key_usages = key_usages(spec);
    params.extended_key_usages = extended_key_usages(spec);
    params.subject_alt_names = subject_alt_names(spec);
    params
}

fn validity_window(label: &str, spec: &X509Spec) -> (time::OffsetDateTime, time::OffsetDateTime) {
    let rsa_bits = (spec.rsa_bits as u32).to_be_bytes();
    let base_time = deterministic_base_time_from_parts(&[
        label.as_bytes(),
        spec.subject_cn.as_bytes(),
        spec.issuer_cn.as_bytes(),
        &rsa_bits,
    ]);

    let not_before = match spec.not_before_offset {
        NotBeforeOffset::DaysAgo(days) => base_time - TimeDuration::days(days as i64),
        NotBeforeOffset::DaysFromNow(days) => base_time + TimeDuration::days(days as i64),
    };
    let not_after = not_before + TimeDuration::days(spec.validity_days as i64);

    (not_before, not_after)
}

fn ca_constraint(spec: &X509Spec) -> IsCa {
    if spec.is_ca {
        IsCa::Ca(BasicConstraints::Unconstrained)
    } else {
        IsCa::NoCa
    }
}

fn key_usages(spec: &X509Spec) -> Vec<KeyUsagePurpose> {
    let mut usages = Vec::new();
    if spec.key_usage.digital_signature {
        usages.push(KeyUsagePurpose::DigitalSignature);
    }
    if spec.key_usage.key_encipherment {
        usages.push(KeyUsagePurpose::KeyEncipherment);
    }
    if spec.key_usage.key_cert_sign {
        usages.push(KeyUsagePurpose::KeyCertSign);
    }
    if spec.key_usage.crl_sign {
        usages.push(KeyUsagePurpose::CrlSign);
    }
    usages
}

fn extended_key_usages(spec: &X509Spec) -> Vec<ExtendedKeyUsagePurpose> {
    if spec.is_ca {
        Vec::new()
    } else {
        vec![
            ExtendedKeyUsagePurpose::ServerAuth,
            ExtendedKeyUsagePurpose::ClientAuth,
        ]
    }
}

fn subject_alt_names(spec: &X509Spec) -> Vec<rcgen::SanType> {
    let mut sorted_sans = spec.sans.clone();
    sorted_sans.sort();
    sorted_sans.dedup();
    sorted_sans
        .into_iter()
        .map(|san| rcgen::SanType::DnsName(san.try_into().expect("valid DNS name")))
        .collect()
}
