//! JWT sign/verify roundtrip using the uselesskey-jsonwebtoken adapter.
//!
//! Demonstrates signing a JWT with RSA, ECDSA, Ed25519, and HMAC keys
//! generated by uselesskey, then verifying each token.
//!
//! Run with:
//! ```sh
//! cargo run -p uselesskey-jsonwebtoken --example jwt_roundtrip --features all
//! ```

use jsonwebtoken::{Algorithm, DecodingKey, Header, Validation, decode, encode};
use serde::{Deserialize, Serialize};

/// Example JWT claims.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct Claims {
    sub: String,
    iss: String,
    exp: usize,
}

fn sign_and_verify(
    alg: Algorithm,
    claims: &Claims,
    enc: &jsonwebtoken::EncodingKey,
    dec: &DecodingKey,
) -> String {
    let header = Header::new(alg);
    let token = encode(&header, claims, enc).expect("signing should succeed");

    let validation = Validation::new(alg);
    let decoded = decode::<Claims>(&token, dec, &validation).expect("verification should succeed");
    assert_eq!(&decoded.claims, claims);

    token
}

fn main() {
    use uselesskey_core::{Factory, Seed};
    use uselesskey_jsonwebtoken::JwtKeyExt;

    let seed = Seed::from_env_value("jwt-roundtrip-example").unwrap();
    let fx = Factory::deterministic(seed);

    let claims = Claims {
        sub: "user-42".to_string(),
        iss: "uselesskey-example".to_string(),
        exp: 2_000_000_000,
    };

    // ── RSA (RS256) ──────────────────────────────────────────────────────
    #[cfg(feature = "rsa")]
    {
        use uselesskey_rsa::{RsaFactoryExt, RsaSpec};

        println!("=== RSA RS256 Sign/Verify ===");
        let rsa = fx.rsa("jwt-issuer", RsaSpec::rs256());
        let token = sign_and_verify(
            Algorithm::RS256,
            &claims,
            &rsa.encoding_key(),
            &rsa.decoding_key(),
        );
        println!("  Token: {}...{}", &token[..20], &token[token.len() - 10..]);
        println!("  Roundtrip verified ✓");
    }

    // ── ECDSA (ES256) ────────────────────────────────────────────────────
    #[cfg(feature = "ecdsa")]
    {
        use uselesskey_ecdsa::{EcdsaFactoryExt, EcdsaSpec};

        println!("\n=== ECDSA ES256 Sign/Verify ===");
        let ecdsa = fx.ecdsa("jwt-issuer-ec", EcdsaSpec::es256());
        let token = sign_and_verify(
            Algorithm::ES256,
            &claims,
            &ecdsa.encoding_key(),
            &ecdsa.decoding_key(),
        );
        println!("  Token: {}...{}", &token[..20], &token[token.len() - 10..]);
        println!("  Roundtrip verified ✓");
    }

    // ── Ed25519 (EdDSA) ──────────────────────────────────────────────────
    #[cfg(feature = "ed25519")]
    {
        use uselesskey_ed25519::{Ed25519FactoryExt, Ed25519Spec};

        println!("\n=== Ed25519 EdDSA Sign/Verify ===");
        let ed = fx.ed25519("jwt-issuer-ed", Ed25519Spec::new());
        let token = sign_and_verify(
            Algorithm::EdDSA,
            &claims,
            &ed.encoding_key(),
            &ed.decoding_key(),
        );
        println!("  Token: {}...{}", &token[..20], &token[token.len() - 10..]);
        println!("  Roundtrip verified ✓");
    }

    // ── HMAC (HS256) ─────────────────────────────────────────────────────
    #[cfg(feature = "hmac")]
    {
        use uselesskey_hmac::{HmacFactoryExt, HmacSpec};

        println!("\n=== HMAC HS256 Sign/Verify ===");
        let hmac = fx.hmac("jwt-secret", HmacSpec::hs256());
        let token = sign_and_verify(
            Algorithm::HS256,
            &claims,
            &hmac.encoding_key(),
            &hmac.decoding_key(),
        );
        println!("  Token: {}...{}", &token[..20], &token[token.len() - 10..]);
        println!("  Roundtrip verified ✓");
    }

    // ── Cross-key verification failure ───────────────────────────────────
    #[cfg(feature = "rsa")]
    {
        use uselesskey_rsa::{RsaFactoryExt, RsaSpec};

        println!("\n=== Cross-Key Failure (expected) ===");
        let key_a = fx.rsa("issuer-a", RsaSpec::rs256());
        let key_b = fx.rsa("issuer-b", RsaSpec::rs256());

        let header = Header::new(Algorithm::RS256);
        let token = encode(&header, &claims, &key_a.encoding_key()).unwrap();

        let result = decode::<Claims>(
            &token,
            &key_b.decoding_key(),
            &Validation::new(Algorithm::RS256),
        );
        assert!(result.is_err());
        println!("  Sign with key_a, verify with key_b → error ✓");
    }

    println!("\nAll JWT roundtrip checks passed!");
}
