//! Cross-backend interoperability tests for uselesskey.
//!
//! Verifies that keys generated by uselesskey work correctly across multiple
//! cryptographic backends (ring, aws-lc-rs, rustls, RustCrypto, jsonwebtoken).
// Cross-backend interoperability tests — see tests/ directory.
